version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: hackathon-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  client-backend:
    container_name: client-backend
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  postgres-data: